version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_later_db
    restart: always
    environment:
      POSTGRES_DB: later
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data