
create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create TABLE IF NOT EXISTS requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 description VARCHAR(255),
 requestor_id BIGINT,
 CONSTRAINT pk_requests PRIMARY KEY (id),
 CONSTRAINT fk_requestor_user FOREIGN KEY (requestor_id) REFERENCES users (id)
);

create TABLE IF NOT EXISTS items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 name VARCHAR(255) NOT NULL,
 description VARCHAR(512) NOT NULL,
 is_available BOOLEAN,
 owner_id BIGINT,
 request_id BIGINT,
 CONSTRAINT pk_item PRIMARY KEY (id),
 CONSTRAINT fk_item_user FOREIGN KEY (owner_id) REFERENCES users (id) ON delete CASCADE,
 CONSTRAINT fk_item_request FOREIGN KEY (request_id) REFERENCES requests (id)
);

create TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status VARCHAR(50),
  PRIMARY KEY (id),
  CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items (id) ON delete CASCADE,
  CONSTRAINT fk_booking_user FOREIGN KEY (booker_id) REFERENCES users (id) ON delete CASCADE
);

create TABLE IF NOT EXISTS comments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
text VARCHAR(255),
item_id BIGINT,
author_id BIGINT,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
CONSTRAINT pk_comments PRIMARY KEY (id),
CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items (id),
CONSTRAINT fk_comments_user FOREIGN KEY (author_id) REFERENCES users (id)
);
